language: c 

sudo: required

services:
 - docker

env:
  matrix:
    - DOCKERFILE=fedora METIS_INT64=OFF
    - DOCKERFILE=fedora METIS_INT64=ON DOCKERHUB=true
    - DOCKERFILE=ubuntu METIS_INT64=OFF
    - DOCKERFILE=ubuntu METIS_INT64=ON DOCKERHUB=true

script:
  - cp -vr docker ${HOME}/docker
  - ln -s ${DOCKERFILE} ${HOME}/docker/Dockerfile
  - cd ../../
  - mv -v ${TRAVIS_REPO_SLUG} $HOME/docker
  - cp -r ${HOME}/.ccache ${HOME}/docker/ccache
  - docker build --build-arg METIS_INT64=${METIS_INT64}
                 -t flecsi/flecsi_tpl:${DOCKERFILE} ${HOME}/docker/ &&
    rm -rf ${HOME}/.ccache &&
    CON=$(docker run -d flecsi/flecsi_tpl:${DOCKERFILE} /bin/bash) &&
    docker cp ${CON}:/home/flecsi/.ccache ${HOME}/

after_success:
  - if [[ ${DOCKERHUB} = true && ${DOCKER_EMAIL} && ${DOCKER_USERNAME} && ${DOCKER_PASSWORD} && ${TRAVIS_PULL_REQUEST} == false && ${TRAVIS_BRANCH} == master ]]; then
      docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push "flecsi/flecsi_tpl:${DOCKERFILE}";
   fi

cache:
  - ccache
