language: cpp

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - ccache
      - cmake
      - cmake-data
      - gcc-5
      - g++-5
      - gfortran-5

before_install:
 - if [[ ${GVER} ]]; then export CC=gcc-${GVER}; export CXX=g++-${GVER}; export FC=gfortran-${GVER}; fi
 - git clone --recursive https://github.com/losalamos/flecsi ../flecsi

env:
  global:
    - CCACHE_CPP2=yes
    - GVER=5

script:
  - mkdir build && cd build && cmake -DENABLE_EXODUS=ON -DENABLE_LAPACK=ON -DENABLE_METIS=ON -DENABLE_SCOTCH=ON -DENABLE_ZLIB=ON -DCMAKE_INSTALL_PREFIX=$HOME/tpl .. && make -j2 && cd ..
  - cd ../flecsi && mkdir build && cd build && cmake -DTPL_INSTALL_PREFIX=$HOME/tpl -DENABLE_PARTITION=ON -DENABLE_IO=ON -DENABLE_UNIT_TESTS=ON .. && make -j2 && make test

cache:
  - ccache
  - apt

compiler:
  - gcc
